### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by ghachey** [pppontusw/dl-nhltv#20]
Hi. Really want to try this out. But getting error below
```
pip3 install .
Processing /Users/myuser/opt/dl-nhltv
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 33, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 516, in load_pyproject_toml
    str(self)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_internal/pyproject.py", line 75, in load_pyproject_toml
    pp_toml = pytoml.load(f)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 11, in load
    return loads(fin.read(), translate=translate, object_pairs_hook=object_pairs_hook, filename=getattr(fin, 'name', repr(fin)))
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 24, in loads
    ast = _p_toml(src, object_pairs_hook=object_pairs_hook)
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 341, in _p_toml
    s.expect_eof()
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 123, in expect_eof
    return self._expect(self.consume_eof())
  File "/Users/myuser/.venvs/nhl/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 163, in _expect
    raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
pip._vendor.pytoml.core.TomlError: /private/var/folders/_3/cj9sf6_n6s73d86d54jkpf9c0000gn/T/pip-req-build-xo_l2n0u/pyproject.toml(4, 1): msg
```
I am running this in a clean venv with the following Python

```
$ python
Python 3.7.1 (default, Nov  2 2018, 12:01:47) 
[Clang 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

I did successfully run the requirements in the venv.

**Comment by pppontusw** [comment]
Thanks for reporting this! I was able to reproduce and fix it so I've released a new version where pip install should work (2.1.1)
