### ISSUE TITLE
docker run auth error

### ISSUE THREAD

**Issue by ghachey** [pppontusw/dl-nhltv#21]
Hi. Me again trying to run using Docker. I run into an authentication error shown below. But I am 100% sure I have the correct username and password as I login the nhllive.com, nhl.tv, etc. websites and Android app with it without issues. Any help getting this to work would be greatly appreciated.

```
Status: Downloaded newer image for pontusw/nhltv:latest
Jan 23 02:38:41 - Logging in to NHL.com..
Jan 23 02:38:43 - There was an error with the request
Jan 23 02:38:43 - Your username and password is likely incorrect
Traceback (most recent call last):
  File "/usr/local/bin/nhltv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/main.py", line 37, in main
    login_and_save_cookie()
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/auth.py", line 36, in login_and_save_cookie
    verify_request_200(req)
  File "/usr/local/lib/python3.8/site-packages/nhltv_lib/auth.py", line 111, in verify_request_200
    raise AuthenticationFailed(msg)
nhltv_lib.exceptions.AuthenticationFailed: Your username and password is likely incorrect
```

**Comment by ghachey** [comment]
I think I got the auth error sorted out. Had different emails in nhl.com and nhl.tv.
