### ISSUE TITLE
dns resolution error when looking up game causes silent death

### ISSUE THREAD

**Issue by pppontusw** [pppontusw/dl-nhltv#9]
```
10/29/19 03:59:42 - Looking up games @ http://statsapi.web.nhl.com/api/v1/schedule?expand=schedule.teams,schedule.linescore,schedule.scoringplays,schedule.game.content.media.epg&startDate=2019-10-26&endDate=2019-10-29&site=en_nhl&platform=playstation
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7feb3d4afc50>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/schedule?expand=schedule.teams,schedule.linescore,schedule.scoringplays,schedule.game.content.media.epg&startDate=2019-10-26&endDate=2019-10-29&site=en_nhl&platform=playstation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb3d4afc50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nhltv", line 11, in <module>
    load_entry_point('nhltv==0.0.2', 'console_scripts', 'nhltv')()
  File "/usr/lib/python3.6/site-packages/nhltv_lib/main.py", line 273, in parse_args
    main()
  File "/usr/lib/python3.6/site-packages/nhltv_lib/main.py", line 94, in main
    download_game(TEAMID)
  File "/usr/lib/python3.6/site-packages/nhltv_lib/main.py", line 27, in download_game
    dl.get_next_game()
  File "/usr/lib/python3.6/site-packages/nhltv_lib/download_nhl.py", line 787, in get_next_game
    json_source = self.check_for_new_game(startDate, endDate)
  File "/usr/lib/python3.6/site-packages/nhltv_lib/download_nhl.py", line 727, in check_for_new_game
    response = self.session.get(url).json()
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='statsapi.web.nhl.com', port=80): Max retries exceeded with url: /api/v1/schedule?expand=schedule.teams,schedule.linescore,schedule.scoringplays,schedule.game.content.media.epg&startDate=2019-10-26&endDate=2019-10-29&site=en_nhl&platform=playstation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb3d4afc50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
```

And then nothing happens, but either of handling and waiting/retrying this error out - or crashing - would be appropriate

**Comment by pppontusw** [comment]
Possible fix in #15
